export const lists = [
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2017/07/AE-1200WHD-1AVDF-399x399.jpg',
        name: 'Casio AE-1200WHD-1AVDF  Nam  Kính Nhựa  Quartz (Pin)  Dây Kim Loại',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 1,
        descript: 'Đồng hồ nam Casio AE1200WHD có mặt đồng hồ vuông to với phong cách thể thao, mặt số điện tử với những tính năng hiện đại tiện dụng, kết hợp với dây đeo bằng kim loại đem lại vẻ mạnh mẽ cá tính dành cho phái nam.',
        brand: 'Casio',
        origin: 'Japan',
        glass: 'Resin Glass (Kính Nhựa)',
        machine: 'Quartz (Pin)',
        insurance: '1',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2019/09/EFR-S567D-1AV-399x399.jpg',
        name: 'Casio EFR-S567D-1AVUDF  Nam  Kính Sapphire  Quartz (Pin)  Dây Kim Loại',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 2,
        descript: 'Mẫu Casio EFR-S567D-1AVUDF thiết kế 3 núm vặn điều chỉnh chức năng Chronograph đầy vẻ nam tính, điểm nhấn nổi bật với phiên bản mặt kính Sapphire dành cho phân khúc Edifice.',
        brand: 'Casio',
        origin: 'Japan',
        glass: 'Sapphire (Kính Chống Trầy)',
        machine: 'Quartz (Pin)',
        insurance: '1',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2021/02/26_AK5000-03A-399x399.jpg',
        name: 'Citizen AK5000-03A – Nam – Quartz (Pin) – Dây Da – Mặt Số 41mm',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 3,
        descript: 'Đồng hồ Doxa D171RWH thiết kế sang trọng đính 8 viên kim cương trên nền mặt số trắng size 40mm, mẫu dây đeo demi vàng hồng tone màu thời trang cho phái mạnh.',
        brand: 'Doxa',
        origin: 'Switzerland',
        glass: 'Sapphire (Kính Chống Trầy)',
        machine: 'Automatic (Tự Động)',
        insurance: '2',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2017/04/34_D171RWH-399x399.jpg',
        name: 'Doxa D171RWH – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 4,
        descript: 'Mẫu Doxa D201RIY thiết kế đơn giản 3 kim trẻ trung với phần vỏ máy vàng hồng kiểu dáng mỏng thời trang 6mm.',
        brand: 'Doxa',
        origin: 'Switzerland',
        glass: 'Sapphire (Kính Chống Trầy)',
        machine: ' Quartz (Pin)',
        insurance: '2',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2018/03/51_D201RIY-1-399x399.jpg',
        name: 'Longines L4.805.4.11.6 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại',
        price: 2000000,
        range: 5,
        gender: 'male',
        id: 5,
        descript: 'Đồng hồ Longines L4.805.4.11.6 có vỏ và dây đeo kim loại mạ bạc sáng bóng, kim chỉ và vạch số La Mã phủ màu đen nổi bật trên nền số màu trắng trang nhã, tạo nên vẻ lịch lãm, sang trọng dành cho phái mạnh.',
        brand: 'Longines',
        origin: 'Switzerland',
        glass: 'Sapphire (Kính Chống Trầy)',
        machine: 'Automatic (Tự Động)',
        insurance: '1',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2017/11/L4.805.4.11.6-399x399.jpg',
        name: 'Doxa D171RWH – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 6,
        descript: 'Mẫu Orient RA-AA0B02R19B phiên bản mạ vàng với mẫu kim chỉ nổi bật trên mặt số size 41.7mm đi kèm thiết kế 2 núm vặn điều chỉnh, vỏ máy kim loại mạ bạc kiểu dáng dày dặn của bô máy cơ.',
        brand: 'Orient',
        origin: 'Japan',
        glass: ' Mineral Crystal (Kính Cứng)',
        machine: 'Automatic (Tự Động)',
        insurance: '1',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2019/07/RA-AA0B02R19B-399x399.jpg',
        name: 'Orient RA-AA0B02R19B – Nam – Automatic (Tự Động) – Dây Kim Loại',
        price: 2000000,
        range: 5,
        gender: 'male',
        id: 7,
        descript: 'Mẫu Orient RA-AA0B02R19B phiên bản mạ vàng với mẫu kim chỉ nổi bật trên mặt số size 41.7mm đi kèm thiết kế 2 núm vặn điều chỉnh, vỏ máy kim loại mạ bạc kiểu dáng dày dặn của bô máy cơ.',
        brand: 'Tissot',
        origin: 'Switzerland',
        glass: 'Sapphire (Kính Chống Trầy)',
        machine: 'Quartz (Pin)',
        insurance: '1',
    },
    {
        image: 'https://cdn3.dhht.vn/wp-content/uploads/2019/05/233_T109.410.36.033.00-399x399.jpg',
        name: 'Tissot T109.410.36.033.00 – Nam – Kính Sapphire – Quartz (Pin) – Dây Da',
        price: 1000000,
        range: 5,
        gender: 'male',
        id: 8,
        descript: 'Mẫu Tissot T109.410.36.033.00 phiên bản sang trọng mạ vàng trên phần vỏ máy kích thước size 38mm, cọc số la mã mỏng cách tân mang lại vẻ trẻ trung lịch lãm dành cho phái mạnh.',
        brand: 'Casio',
        origin: 'Japan',
        glass: 'Resin Glass (Kính Nhựa)',
        machine: 'Quartz (Pin)',
        insurance: '1',
    },

]


export const reports = [
    // {
    //     item: '2',
    //     name: 'Nguyen Van A',
    //     des: 'Đồng hồ tốt',
    //     time: '7 giây trước',
    //     img: 'OIP1.jpg'
    // },
    // {
    //     item: '2',
    //     name: 'Tran Thi B',
    //     des: 'Đồng hồ bị lỗi',
    //     time: '45 giây trước',
    //     img: 'OIP.jpg'
    // },
    // {
    //     item: '3',
    //     name: 'Tran Thi B',
    //     des: 'Đồng hồ bị lỗi',
    //     time: '45 giây trước',
    //     img: 'OIP.jpg'
    // },
    // {
    //     item: '4',
    //     name: 'Tran Thi B',
    //     des: 'Đồng hồ bị lỗi',
    //     time: '45 giây trước',
    //     img: '../shared/image/OIP1.jpg'
    // },
]